### ISSUE TITLE
cmd_calc /lib && cmd_check /lib => Jacksum: new files (NEW): 493153; version 3.1.0

### ISSUE THREAD

**Issue by BlindDuck** [jonelo/jacksum-fbi-linux#1]
While playing around with the new version 3.1.0:

jacksum cmd_calc /lib && jacksum cmd_check /lib
=> Jacksum: new files (NEW): 493153

-rw-r--r-- 1 root  root    49768066 Jan  8 17:21 /tmp/jacksum.8534.txt
-rw-r--r-- 1 joerg disk        4322 Jan  8 17:19 /tmp/jacksum.8049.txt
-rw-r--r-- 1 joerg disk     9396307 Jan  8 17:19 /tmp/jacksum.txt
[jacksum.txt.tar.gz](https://github.com/jonelo/jacksum/files/7833583/jacksum.txt.tar.gz)

May be I configured something wrong during the update from 1.7.0 to 3.1.0:
[jacksumJK.sh.tar.gz](https://github.com/jonelo/jacksum/files/7833574/jacksumJK.sh.tar.gz)

/opt, /boot and /lib64 worked fine

Any Hints/explainations are welcome.

**Comment by jonelo** [comment]
I have fixed a bug that is related to this ticket. See also https://github.com/jonelo/jacksum/issues/17
