### ISSUE TITLE
support Plasma 6 [was: "not working under kubuntu 24.10"]

### ISSUE THREAD

**Issue by erasmo52** [jonelo/jacksum-fbi-linux#10]
Dear friend,
I downloaded and tried to install the Jacksum File Browser Integration for Linux 2.7.0 release but it seem not to be compatible with kubuntu oracular.
When I run ./jacksum-file-browser-integration.sh every option (except the Gnome Nautilus option) is marked DISABLED and it is not possible to apply.
Maybe you should produce a new release for working under the kubuntu 24.10, or is there some trick to employ?
It would be nice to have a new working release because it is a very useful tool.
I thank you for your job
have a nice time
Erasmo

**Comment by jonelo** [comment]
Hi Erasmo,

thank you for the report. I can reproduce the issue using Kubuntu 24.10 which uses [Plama 6](https://wiki.ubuntu.com/OracularOriole/ReleaseNotes/Kubuntu#Plasma_6.1:_Replacing_Plasma_5_in_Kubuntu.). So Dolphin expects the servicemenus in a [different directory](https://develop.kde.org/docs/apps/dolphin/service-menus/) again.

I am going to do some tests and update the install script soon. Stay tuned.

-Johann

**Comment by jonelo** [comment]
deja vu. LOL. In April 2024 I already pushed KDE 6 support to the master branch. So the updated script is already there. I just didn't make a release.

**Comment by jonelo** [comment]
v2.8.0 released. Give it a try.

**Comment by erasmo52** [comment]
Hi Johann,
sorry for my late reply.
Finally I installed your update and all is working fine.
I thank you for your job
Erasmo
