### ISSUE TITLE
use zenity instead of Kate for less intrusive interaction

### ISSUE THREAD

**Issue by eadmaster** [jonelo/jacksum-fbi-linux#2]
using kate will switch the current active tab in the editor (annoying). Zenity (or kdialog on KDE) is probably a better default choice for this. e.g.:

````
cat /tmp/jacksum.50865.txt | zenity --text-info --width 777 --height 400
````

**Comment by jonelo** [comment]
Thank you for the suggestion 👍. I did a quick test and I like it already. Does not seem to have problems with large files, and it has a version option which is good for compatibility reasons. Will also add `--title`, `--no-wrap`, and `--font="Monospace"` to the zenity call probably. Need to check features of kdialog as well.

**Comment by jonelo** [comment]
https://github.com/jonelo/jacksum-fbi-linux/releases/tag/v2.0.0 is on the web.
